name:                aoc
version:             0.1.0.0
github:              "jackmatusiewicz/aoc"
license:             BSD3
author:              "Jack Matusiewicz"
maintainer:          "example@example.com"
copyright:           "2021 Jack Matusiewicz"

data-dir: data

extra-source-files:
- README.md
- ChangeLog.md
data-files:
- DayOneData.txt
- DayTwoData.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jackmatusiewicz/aoc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
